### ISSUE TITLE
build error: file RPATH_CHANGE could not write new RPATH

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [darlinghq/darling#1072]
**Build Log**
```
CMake Error at src/kernel/cmake_install.cmake:55 (file):
  file RPATH_CHANGE could not write new RPATH:

    

  to the file:

    /usr/local/libexec/darling/usr/lib/system/libsystem_kernel.dylib

Call Stack (most recent call first):
  src/cmake_install.cmake:56 (include)
  cmake_install.cmake:315 (include)

```

**System Information**
arch linux

| Clang | 13.0.0 |
| CMake | 3.22.0 |
| Linux Kernel | 5.15.4 |
| Darling | latest git build |

**Comment by minfs** [comment]
I'm using Arch and some newer CMake version, I received this error as well; however, rebuilding it again possibly could work. I was trying to find other instances where that CMake error appeared, but none related to it; try to rebuild, but that's all I can suggest because that's what I did to build it

**Comment by Etaash-mathamsetty** [comment]
> 

I have tried 3 times

**Comment by Etaash-mathamsetty** [comment]
> I'm using Arch and some newer CMake version, I received this error as well; however, rebuilding it again possibly could work. I was trying to find other instances where that CMake error appeared, but none related to it; try to rebuild, but that's all I can suggest because that's what I did to build it

some newer cmake version?
3.22.0 is the newest stable though

**Comment by Etaash-mathamsetty** [comment]
trying again with ninja
