### ISSUE TITLE
Somebody got iOS code running on Android but it was never released and frogotton

### ISSUE THREAD

**Issue by upintheairsheep** [darlinghq/darling#1168]
Cycada/Cider
https://systems.cs.columbia.edu/projects/cycada/
IT WORKS! It was never released, but you should attempt to contact the developers by any means possible for feedback. If the project was legally reverse engineered, you should integrate Cycada code in here and boost the progress significantly. Also tell them to release the project on GitHub even if it has copyright issues.
http://jeremya.com/files/pub/2014/03/cider-asplos2014.pdf
http://jeremya.com/files/pub/2014/03/cider/
https://www.youtube.com/watch?v=Uaple0Ec1Dg
http://jeremya.com/files/pub/2014/03/cider-asplos2014.bib
https://en.wikipedia.org/wiki/Columbia_Cycada
https://apple.fandom.com/wiki/Columbia_Cycada

**Comment by LubosD** [comment]
I even worked on a re-creation of this for a Chinese company and they have succeeded in less than a year, but it was also never released.

You know why? Because this approach is based on pirating the complete iOS userspace and patching the Linux kernel so that it supports XNU syscalls.

Nice hack, but completely illegal.

**Comment by upintheairsheep** [comment]
> I even worked on a re-creation of this for a Chinese company and they have succeeded in less than a year, but it was also never released.
> 
> You know why? Because this approach is based on pirating the complete iOS userspace and patching the Linux kernel so that it supports XNU syscalls.
> 
> Nice hack, but completely illegal.

Video for proof?

**Comment by LubosD** [comment]
I don't have one, it's too long ago.

**Comment by upintheairsheep** [comment]
> I even worked on a re-creation of this for a Chinese company and they have succeeded in less than a year, but it was also never released.
> 
> You know why? Because this approach is based on pirating the complete iOS userspace and patching the Linux kernel so that it supports XNU syscalls.
> 
> Nice hack, but completely illegal.

Name of the company?

**Comment by upintheairsheep** [comment]
It could be legal if you need an old iOS device that is jailbroken and it extracts stuff from there.

**Comment by CuriousTommy** [comment]
> It could be legal if you need an old iOS device that is jailbroken and it extracts stuff from there.

@upintheairsheep The whole point of Darling is to not be dependent on Apple's proprietary code in order to run your macOS/iOS app. Darling will **NEVER** support running off of an official macOS/iOS install.

---

**Mini Rant**: Legal issues aside, I feel like some people misunderstand the point of Darling. It's not just about running macOS/iOS apps on Linux. It's also about better integrating these app into the Linux ecosystem (drag and drop, printing, using Linux accessibility tools on a macOS app, etc.).

You don't get that type of integration if we stick with Apple's proprietary code.

**Comment by upintheairsheep** [comment]
I’m just asking the name of the Chinese company Sent from my iPhoneOn Oct 13, 2022, at 9:09 AM, CuriousTommy ***@***.***> wrote:﻿

It could be legal if you need an old iOS device that is jailbroken and it extracts stuff from there.

@upintheairsheep The whole point of Darling is to not be dependent on Apple's proprietary code in order to run your macOS/iOS app. Darling will NEVER support running off of an official macOS/iOS install.

Mini Rant: Legal issues aside, I feel like some people misunderstand the point of Darling. It's not just about running macOS/iOS apps on Linux. It's also about better integrating these app into the Linux ecosystem (drag and drop, printing, using Linux accessibility tools on a macOS app, etc.).
You don't get that type of integration if we stick with Apple's proprietary code.

**Comment by CuriousTommy** [comment]
> I’m just asking the name of the Chinese company 

Just be mindful that LubosD may not be comfortable sharing that information with you.
