### ISSUE TITLE
[Proposal] Add Tag In Darling

### ISSUE THREAD

**Issue by cheznewa** [darlinghq/darling#1171]
Hi/Hello, Is Possible To Add Tag Software ::::::: https://github.com/jdberry/tag (In MIT Licence)
This Program (For macOS Only) Is To Tagged Keywords A File
And I Proposal It Because This Repo No Binary Precompled.

**Comment by CuriousTommy** [comment]
Generally speaking, we only want to include program/libraries that would be provided in a real install of MacOS. Since the tag software is not provided on a clean install of MacOS, it doesn't really make a lot of sense to include it as part of the build process.

If you want precompiled build, you should as the owner of the repo to provide one.
