### ISSUE TITLE
Darlingserver can not succeed to call bsdcreate_thread for GraalVM 21.0.0.2.

### ISSUE THREAD

**Issue by vonjackustc** [darlinghq/darling#1218]
**Expected Result**
To call the application "graalvm-ce-java8-darwin-amd64-21.0.0.2/Contents/Home/bin/js", the old LKM version can succeed to execute.

**Actual Result**
The result from darlingserver is "Failed to create socket", then "Segmentfault 11".

**Steps To Reproduce**
Directly to call this application.

**System Information**
CentOS 8.5 with core updated

| Software | Version |
| --- | --- |
| Linux Kernel | 5.4.214-1.el8.elrepo.x86_64 |
| Darling | 81f2aadfc1ab38850f6d9a2ec391d4cc90707592 |

**xtrace logs**
[xtrace_lkm.log](https://github.com/darlinghq/darling/files/9612345/xtrace_lkm.log)
[xtrace_server.log](https://github.com/darlinghq/darling/files/9612346/xtrace_server.log)

**GraalVM JS Binary**
[js.tgz](https://github.com/darlinghq/darling/files/9612370/js.tgz)

**Comment by facekapow** [comment]
Sorry for the long delay; I'm unable to reproduce this locally, both with the binary you provided and the original binary in the GraalVM release. Thank you for providing the xtrace logs, but unfortunately they don't indicate why this is happening.

However, we can look at the source code where this error would occur: https://github.com/darlinghq/darling/blob/8e028983e51b134bf00c0dd7352ad22cb574c35b/src/startup/mldr/elfcalls/threads.c#L212-L217

Now let's look at `__mldr_create_rpc_socket`: https://github.com/darlinghq/darling/blob/8e028983e51b134bf00c0dd7352ad22cb574c35b/src/startup/mldr/mldr.c#L693

So there are only a few places where this could fail:

  * `socket` fails - Unlikely, since this occurs early in the process and the xtrace logs show that other `socket` calls succeeded
  * `socket_bitmap_get` fails - Unlikely, since there's only a single thread in the system
  * `dup2` fails - Unlikely, for the same reason as `socket`
  * `fcntl` fails - *Extremely* unlikely, since all it does is set `FD_CLOEXEC`
  * `bind` fails - Now *this* is likely where the fault is

It's very likely that the issue occurs with `bind`, since we rely on Linux's abstract namespace autobind feature. This has a system-wide limit of 2^20 autobound addresses, which is a lot, but it's possible that it was exhausted on your system.

My recommendation is just to try it again. If it happens again, try to get the core dump if you can (see https://docs.darlinghq.org/contributing/debugging.html#debug-with-core-dump).

**Comment by facekapow** [comment]
Oh, I almost forgot: also try updating Darling. I tested on the current master branch (8e028983e51b134bf00c0dd7352ad22cb574c35b) and (like I said) I was able to run the binaries just fine. It's possible some commit between the one you used and the current one foxed the issue.

**Comment by facekapow** [comment]
Closing this since I was unable to reproduce the issue and there was no response. Feel free to reopen this if you're still running into it.
