### ISSUE TITLE
ICU not necessary

### ISSUE THREAD

**Issue by soloturn** [darlinghq/darling#1255]
swift nowadays builds with standard ICU on linux. so darwin should use standard ICU as well, isn't it?

https://aur.archlinux.org/packages/swift-language
https://src.fedoraproject.org/rpms/swift-lang/blob/rawhide/f/swift-lang.spec

**Comment by facekapow** [comment]
If you're referring to the version of ICU that we build (i.e. https://github.com/darlinghq/darling-icu), we will always have to build that with Darling because we need the Mach-O version of the library (which may have some Apple-specific patches as well), not the ELF version included with standard Linux installs.

**Comment by soloturn** [comment]
ah, you need the mach-o version for the emulation?

**Comment by facekapow** [comment]
Yeah.
