### ISSUE TITLE
rm -r fails to remove directories

### ISSUE THREAD

**Issue by SomeDevHere** [darlinghq/darling#1383]
**Expected Result**
Directory is deleted

**Actual Result**
Directory is kept and rm fails with `Is a directory`

**Steps To Reproduce**
1. Create an empty directory `mkdir tmp`
2. Delete the directory `rm -r tmp`

**Xtrace Log**
[xtrace.log](https://github.com/darlinghq/darling/files/11699572/xtrace.log)

**Additional Information**
This error seems to happen because Darling is ignoring the flag `AT_REMOVEDIR_DATALESS` when passed to `unlinkat`.

**System Information**

| Software | Version |
| --- | --- |
| Linux Kernel | 6.3.6-arch1-1  |
| Darling | 894d62c91d78d56e05708f40f2d7e490fce5f046  |

**Comment by wjc404** [comment]
I got the same issue when using darling(built from master branch yesterday) on WSL2(ubuntu-22.04):
![image](https://github.com/darlinghq/darling/assets/52632443/f92f2b59-8db9-4baf-a3e2-6c39c4afdae6)

**Comment by bugaevc** [comment]
`atflags_bsd_to_linux` needs to handle `AT_REMOVEDIR_DATALESS`

**Comment by bugaevc** [comment]
On top of that it should reject unknown flags with `EINVAL`, which is what `rm` expects to see if the kernel doesn't support `AT_REMOVEDIR_DATALESS`

**Comment by bugaevc** [comment]
XNU has these `AT` flags:

* `AT_EACCESS` -- Linux has that too, we could just convert it, or ignore it, depending on what we want to do about UID/setuid
* `AT_SYMLINK_NOFOLLOW`, `AT_SYMLINK_FOLLOW`, `AT_REMOVEDIR` -- these we handle already
* `AT_REMOVEDIR_DATALESS`, which is what this bug is about -- same as `AT_REMOVEDIR`, but don't materialize the dir first if it's _dataless_. Dataless files are apparently some sort of placeholders for real files that can be "materialized" into full files with help from `filecoordinationd` -- and by default, dataless files are automatically and transparently materialized, unless you explicitly ask not to, and `AT_REMOVEDIR_DATALESS` is one way of doing that. Since we don't and are not going to have anything like dataless files in Darling, it's safe to treat `AT_REMOVEDIR_DATALESS` just like `AT_REMOVEDIR`
* `AT_REALDEV` -- seems to impact what `st_dev` gets returned for `fstatat`, not sure how exactly; we could just ignore it since we virtualize VFS/mounts/devices anyway
* `AT_FDONLY` is Linux's `AT_EMPTY_PATH`

Anything else -> `EINVAL`

**Comment by niansa** [comment]
Maybe it should be checked how Darwin handles fat32 volumes which don't support dataless files either

**Comment by mrhhug** [comment]
Can confirm the fix at : https://github.com/darlinghq/darling-xnu/pull/2
remediates the `rm -rf ` directory issue on my current kernel : 6.4.3-arch1-2
