### ISSUE TITLE
Compile all COMPONENTS by default

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1493]
I would change the default setting to compile all, will prevent useless bug reports:
```
cmake -DCOMPONENTS="all" ..
```
If the user want to compile less, let him decide.

**Comment by HinTak** [comment]
This is just going backwards. A few years ago, javascriptcore was included, and it was the source of at least two classes of bug reports: (1) people complaining it takes too long - despite it saying 95% done, it was about 1/3 of the total CPU consumption, so it looks as it is is stuck, (2) most of the files include the same headers and emits the same warnings over and over - if you don't look carefully, it looks as if it is in an infinite loop.

So that fact that jsc takes hours to compile (and about 1/3 of build time despite saying '95%' at start), and emit the same warnings over and over for hours, was the source of many bug reports.

My $0.02.

**Comment by superbonaci** [comment]
Maybe the 95% log feature should be changed to reflect some progress, and display warnings differently.

**Comment by CuriousTommy** [comment]
For now it doesn't really make sense to include JSC. In the distant future, we can look into including JSC when it makes sense too. Also `-DCOMPONENTS="all"` include some stuff most users don't need.
