### ISSUE TITLE
Question about Darling's capabilities

### ISSUE THREAD

**Issue by Melab** [darlinghq/darling#155]
The homepage for Darling said at one point that it could run the Xcode toolchain. I understand that it cannot run the graphical elements, but to what degree is it able to run the toolchain? All of it, just as if one were to use the command line instead the GUI to create and build an Xcode project?

**Comment by LubosD** [comment]
You can run the compiler, but I'm afraid you cannot run other xcode stuff at this moment, because there are some massive dependencies. It remains at the top of my list of stuff to do.

**Comment by Melab** [comment]
So does that mean the tools like `xcrun` and `xcodebuild` will not work?

**Comment by LubosD** [comment]
No, they don't work at this moment. I'm still looking for volunteers, but while there are many people who'd like to use Darling, there are very few willing to contribute their time.

**Comment by cesss** [comment]
I'd contribute my time if I had it, but, let me assure you that this project is very important. And it's today more important than ever, because of how Apple is treating the Mac. I'm yet another one of those who would be using Darling today if it was functional, but who doesn't have time for contributing. I just can try to encourage you to continue, even far beyond being able to run an Xcode toolchain (I suppose you know, but GNUstep could be of great help when moving to support UI apps, as they've tried to keep the API 100% compatible with the official Apple Cocoa). Anyway, being able to run an Xcode toolchain would already be very important, and, in fact, I would become a Darling user as soon as a command-line toolchain works.

**Comment by cesss** [comment]
BTW, if we exclude xcrun, xcodebuild and any other tool whose name starts with "xcode", do the rest of command line developer tools work? I mean, the compiler, the linker, lipo, etc... do they work? I'm asking this because I'm just using these command line tools when building wxWidgets app bundles in OS X, so maybe I'd be able to already get the task done in Darling!!

**Comment by LubosD** [comment]
@cesss Yes, they work. There's an example use of clang here: https://www.darlinghq.org/introduction/

**Comment by cesss** [comment]
Oh!! That's too cool!! This means I can start using Darling today! And perhaps my command line apps, which don't use any framework, might even work! BTW, because I'm using wxWidgets for my GUI apps, I tend to build two versions: One Cocoa-based, and another one X11-based. I'm guessing that the X11 version of my apps could be quite close to get working, because I'm not using any framework there (although I'm linking with OpenGL, which I guess isn't translated on Darling yet). Anyway, being able of running the command line developer tools means that I can start using Darling today!!!

**Comment by ahyattdev** [comment]
Just make sure you use the macOS SDK with Clang, as the libraries Clang would need to link aren't accessible to the prefix. 

Please report any issues you run into, or suggestions you may have.
