### ISSUE TITLE
Alias CFSTR() to clang builtin

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#209]
#define `CFSTR()` to `__builtin___CFStringMakeConstantString()`.

The CFSTR implementation in CoreBase sucks big time, it requires additional setup at runtime and it is not a constant expression, which breaks libsecurity_transform build.

**Comment by ahyattdev** [comment]
The macOS 10.12 sources are up. CoreFoundation has been marked as "Coming Soon" since the 10.11 sources went up. If they open source it soon, would replacing CoreBase with it be feasible?

Also, the Apple libdispatch is open source. Some functions and types that were added starting with Yosemite to libdispatch are missing from the implemtation for Linux that Darling currently uses. If libdispatch from Apple Open Source doesn't work, we could instead use the [libdispatch fork maintained by the Swift project](https://github.com/apple/swift-corelibs-libdispatch), which is known to work on Ubuntu.

**Comment by LubosD** [comment]
There are many older versions of CFLite available, so we could always use those. CFLite mainly lacks bridging support (NSCF* classes), which could be supplemented by files from CoreBase.

The problem with Apple's CFLite is it requires Apple's libdispatch (e.g. `_dispatch_get_main_queue_port_4CF`) and Apple's libdispatch needs Mach IPC features we don't have (e.g. Mach vouchers, but it seems this one can be turned off).

So eventually, we definitely want to use Apple's CFLite and libdispatch, but I'm afraid it would be a setback for the time being. The best thing would be to port XNU's Mach IPC into a Linux kernel module as a replacement for what we use now.

**Comment by LubosD** [comment]
Done.
