### ISSUE TITLE
Processes retain old /dev/mach fd across execve

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#229]
To reproduce, in one tab:

```
$ darling shell
Darling [~]$
```

In another:

```
$ ls -l /proc/[pid]/fd
total 0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 0 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 1 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:37 2 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 255 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 3 -> /Volumes/SystemRoot/dev/mach
```

Back to Darling shell:

```
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
Darling [~]$ exec bash
```

Back in the other tab:

```
$ ls -l /proc/[pid]/fd
lrwx------ 1 sergey sergey 64 Jan 10 15:40 0 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 1 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:51 10 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 11 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:37 2 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 255 -> /dev/pts/0
lrwx------ 1 sergey sergey 64 Jan 10 15:40 3 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 4 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 5 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 6 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 7 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 8 -> /Volumes/SystemRoot/dev/mach
lrwx------ 1 sergey sergey 64 Jan 10 15:51 9 -> /Volumes/SystemRoot/dev/mach
```

**Comment by bugaevc** [comment]
Keeping the old file descriptor is probably the right thing to do, so it should not open a new one but pick up the passed one instead.

This can be implemented by iterating over open file descriptors and seeing if any of them is connected to `/dev/mach`, opening a new one otherwise.

**Comment by LubosD** [comment]
Actually no, it should open a new one. So a O_CLOEXEC should fix this.

**Comment by bugaevc** [comment]
Ah, okay, but please explain why? Does executing another file change the process data from Mach's perspective?

**Comment by LubosD** [comment]
Yes, opening a new descriptor creates a new Mach port namespace. The old descriptor refuses any new calls if it was opened for a different PID.

**Comment by LubosD** [comment]
This is because unlike fd's, Mach ports are never inherited (not even across fork) with the exception of a few special ports - e.g. the bootstrap port, which should in future serve as a communication channel to launchd.

And launchd won't work until we have kqueue with support for Mach ports + full Mach port set support in Darling. I'm just not sure...

* Whether we should keep using libkqueue or try to do this in the kernel along with Mach port support. This is because our Mach port (right) numbers are not FDs (and should not be!) and therefore cannot be used with epoll.
* Whether we should keep mending/improving darling-mach code or try to port the original XNU code over.

**Comment by bugaevc** [comment]
> And launchd won't work until we have kqueue with support for Mach ports + full Mach port set support in Darling.

Why do we want launchd in the first place? Do apps rely on it for some of their functionality?

> Whether we should keep using libkqueue or try to do this in the kernel along with Mach port support. This is because our Mach port (right) numbers are not FDs (and should not be!) and therefore cannot be used with epoll.

Am I understanding this correctly? You're saying that the options are:
* Make `/dev/mach` pollable, add a couple of new `ioctl`s to add or remove ports from the "poll set", patch libkqueue to support this (wouldn't this cause issues with multithreading?). This keeps `darling-mach` to the Mach part of it.
* Implement kqueue in the kernel module, with lots of new ioctls. Are there any downsides? (what I can think of: the less code in the kernel space, the better -- in terms of security and stability).

By the way, why is Mach emulation implemented in the kernel and not in userspace, a la wineserver?

> Whether we should keep mending/improving darling-mach code or try to port the original XNU code over.

Is there still a lot to add/improve in the lkm? I thought it was pretty much ready except port sets & kqueue. Also, I was under impression that Mach/XNU internal architecture is so different from that of the Linux kernel that it would make sense to reimplement its interface as a module, but not to reuse code directly.

**Comment by LubosD** [comment]
> Why do we want launchd in the first place? Do apps rely on it for some of their functionality?

Absolutely. launchd also functions as the "bootstrap server" meaning it maps service names to mach ports and along with libxpc enables communication with services, e.g. notifyd or securityd (basically anythingD).

Various software also installs system services to be started at boot and also expects to be able to call launchctl to start/stop them manually. launchd is actually a nice piece of software, it's like systemd before it became this horrid monster.

> Am I understanding this correctly? You're saying that the options are: [...]

Yes, except making `/dev/mach` pollable is possibly not so easy (you need to specify somehow for what port/port set you're polling).

> By the way, why is Mach emulation implemented in the kernel and not in userspace, a la wineserver?

Because wineserver is Wine's disaster. It is one of the most important reasons why Wine is so slow with so many apps. For example, every time a Win32/64 app creates a mutex and locks/unlocks it, it creates lots of roundtrips between the process and wineserver, because mutex is an object that can be shared between processes, so it must exist as a centrally managed entity.

The situation could potentially change with kdbus, sorry, bus1, but I've been waiting for it for years and it is still not in the kernel...

> Is there still a lot to add/improve in the lkm?

It is actually a small miracle you haven't encountered system freezes / crashes etc. The code is complicated, full of tons of complex locking scenarios and possible mistakes.

> I thought it was pretty much ready except port sets & kqueue. 

There is more, we don't have the Mach vouchers feature and basically any advanced functionality is missing. OTOH, it has done the job until now, but libc has been its only "client" for now... I'm really at a loss here.

> Also, I was under impression that Mach/XNU internal architecture is so different from that of the Linux kernel that it would make sense to reimplement its interface as a module, but not to reuse code directly.

Well, every kernel has similar primitives and operations. The NextBSD guys have actually ported the Mach IPC code over to FreeBSD and it works.

I think the most complicated part of this job would be to correctly replicate the API defined here: http://unix.superglobalmegacorp.com/xnu/newsrc/osfmk/kern/wait_queue.h.html
because this is at the heart of message passing.
