### ISSUE TITLE
Trouble runnning Java

### ISSUE THREAD

**Issue by ARautenberg** [darlinghq/darling#253]
Running Ubuntu Server 16.04 in a VM.

I build the whole darling project as root and I started darling shell as root.

1. I transfered the Java Installation from my Mac to the VM.
2. Setting JAVA_HOME and PATH in .dshellrc followed by souce .dshellrc
3. java -version shows
dyld: Cannot execute binary file: Failed to load native library: /Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/libSecurity.so: undefined symbol: kSecXPCKeyString

Any ideas where to look/what to do?

Thanks for taking time to read this!

**Comment by bugaevc** [comment]
This is actually a known issue, and I have a fix locally, let me commit & push it...

**Comment by ARautenberg** [comment]
I will rebuild and install darling asap and let you know about the result. Thank you so much!

**Comment by bugaevc** [comment]
Try updating (`git pull && git submodule init && git submodule update`) and rebuilding. The issue should be fixed

**Comment by bugaevc** [comment]
...but I'm not sure it's the only thing that prevents Java from running. Please report your findings ;)

**Comment by ARautenberg** [comment]
Now I get this:
dyld: Cannot execute binary file: Failed to load native library: /Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/libSecurity.so: undefined symbol: CC_SHA384

**Comment by bugaevc** [comment]
This is a known issue too. Unfortunately, it's not as easy to fix. `CC_SHA384` is defined in CommonCrypto, which we can't build because it requires CoreCrypto, a small cryptographics library, which is not open-source.

It'd be _super great_ if someone stepped in and reimplemented it. See https://www.darlinghq.org/developer-zone/low-hanging-fruit/ for some more details and https://github.com/darlinghq/darling-corecrypto for the current state of the reimplementation.

(Btw @LubosD told me the situation should be better in the upcoming Mach-O branch.)

**Comment by LubosD** [comment]
FYI, I haven't yet successfully launched JVM under Darling. This is definitely on the radar, e.g. to get Jenkins/TeamCity agents to run in Darling's containers, but the Security framework remains a significant hurdle.

The source code of Security is publicly available, but it has external dependencies that are not + it's a really huge beast, so even writing the build files requires a considerable effort.

**Comment by bugaevc** [comment]
@ARautenberg: Please retest with the latest version of Darling, @LubosD's Mach-O work has landed some time ago.

**Comment by LubosD** [comment]
We're not building Security yet, so.... it still won't work.
