### ISSUE TITLE
Error when running shell

### ISSUE THREAD

**Issue by flyingP0tat0** [darlinghq/darling#296]
Hi,

I installed darling following the wiki instructions, no errors there.
Now I am trying to start darling shell but the following error hits me every time:
`bash: __bp_precmd_invoke_cmd: command not found`
As I have no idea what this is about, maybe someone can tell me what the problem is.

Thanks

**Comment by LubosD** [comment]
Maybe something in your .bashrc / .bash_profile?

**Comment by bugaevc** [comment]
See flatpak/flatpak#381 for a similar issue.

`__bp_precmd_invoke_cmd` was likely put into your `PROMT_COMMAND` by your distro's defaults, and it is being inherited into the Darling Shell. The fix for now would be to unset `PROMT_COMMAND` [when spawning the shell](https://github.com/darlinghq/darling/blob/master/src/startup/darling.c#L334-L336) (want to do a Pull Request?); in the long term, we're going to have the shell spawned from a fresh environment, only inheriting parts of the environment that we need (such as `DISPLAY`).

**Comment by flyingP0tat0** [comment]
It looks like I screwed up something, so I decided to create a docker image for darling.
