### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [darlinghq/darling#347]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by flyingP0tat0** [comment]
I would appreciate this as well. This is very important to distribute this awesome piece of software.
Are there any plans @LubosD?

**Comment by LubosD** [comment]
@flyingP0tat0 Yes, that would be very nice. We're currently busy with doing some rearchitecturing to make LLDB usable, because the lack of debugging facilities make development a real PITA (and much slower than it could be).

To put things into perspective, we're on the verge of finally having some GUI support, but solving any issues takes hours when all you can see in GDB is disassembly....

**Comment by flyingP0tat0** [comment]
@LubosD Take your time, what you guys do is awesome. Just remember to tag a version when you feel it is time to do so.

**Comment by ahyattdev** [comment]
We are doing releases now, with packages available for download on GitHub
