### ISSUE TITLE
More permissive licensing

### ISSUE THREAD

**Issue by ryao** [darlinghq/darling#35]
The GPLv3 is a problem for developers who are building software in your environment because everything linked against a GPLv3 licensed library must also be GPLv3 licensed. This causes plenty of people to stay away from GPLv3 licensed projects. It would be better for your project's adoption among developers if it adopted the LGPL like Wine did or the X11 license that Wine originally used. It would be easier to do this now when there are only 6 contributors than it would be to do this when there are more contributors.

**Comment by wjk** [comment]
@LubosD I would also like to chime in on this. I agree with the points made by @ryao above. In addition, it is my understanding (although IANAL) that the Apple Public Source License and the GPL (any version) are not compatible, which means that mixing code under those licenses and distributing it is not possible without violating the terms of the GPL.

If I may suggest, would you consider relicensing (part of) Darling under the Mozilla Public License version 2.0? This license still requires that modified source files be released, which was your main concern as stated above, but it does not place as many restrictions on Darling users as the LGPL does. (For example, the LGPL requires that the user be able to replace the LGPLed code with their own, modified versions and have the app still launch. This is not possible on any of the popular "app store" platforms due to code-signing requirements that prevent modified apps from launching, even if the modification is permitted by the software vendor.)

**Comment by uliwitness** [comment]
It might be worth contacting the FSF about this. Back when the OpenCard/FreeCard project was a thing, we actually got them to come up with an exception clause we could add to our code that made it GPL, but allowed people to build standalone versions of their documents that embedded the application without them being considered derivative works. Admittedly, that was over a decade ago, but they were very polite and forthcoming back then.

**Comment by LubosD** [comment]
Just because different parts of Darling use incompatible licenses, doesn't mean that the result cannot be distributed. If you compile a GPL-licensed app on OS X, you can still distribute the resulting binary, even though parts of OS X are licensed under APSL.

I find it rather sad, however, that there are more people talking about the right license and almost nobody contributing code :-(

**Comment by Maxqia** [comment]
Well, can you change the license from GPLv3 to GPLv2, because this project possibly could become a  part of the Linux kernel for better binary compatibility for *BSD (and Mac) software.

**Comment by bugaevc** [comment]
To quote Linus Torvalds:

> Nobody has the right to whine about another persons choice of license. You have a choice: use it or don't. Complaining about the license to the author isn't part of it.

**Comment by cesss** [comment]
When choosing open source libraries for my projects, I always avoid copyleft licenses, because they limit my freedom (including my freedom to release any derived works under MIT license, for example). If SDL 2 was copylefted, I wouldn't be using it. The same happens when I release code, I never choose copyleft because I wish my code will be used by everybody, no matter their licensing preferences. Copyrighted open source pleases everybody (copyleft developers included).

Yes, as you said, others can monitize your effort. You don't get their money, but you get maximum possible deployment for your work.

As others said, everybody is free to choose their license. I respect it. I'm only saying that if Darling had some use inside another software, I wouldn't use it in a project of mine unless it was MIT/BSD/etc licensed.

I'm not pickier than others. Otherwise, quite a few commercial companies wouldn't be offering a copyleft license for free and a copyright license if you pay. Nobody would buy such licenses if my preferences weren't popular. The deal they offer is freedom for money. MIT/BSD/etc licenses offer maximum freedom for free.

**Comment by bugaevc** [comment]
@cesss It's not at straightforward as you're trying to make it sound. Copyleft vs permissive is a highly debatable topic, the argument for copyleft (that does not necessarily represent my opinion) being that despite copyleft licenses limiting some of your freedoms (namely, the freedom to distribute modified work without making it copyleft), they give you more freedom in the long term, because they ensure that no proprietary fork can overtake the original (or even exist) -- others are forced to give their work back to the community, and in the end everyone gets a better product.

> But, if your goal is maximum widespread use of Darling for whatever purpose, then the way to go is MIT/BSD/etc.

Well, if you compare the popularity of BSD to that of GPL'ed GNU & Linux... On the other hand, see the iOS situation: it uses code from FreeBSD, Apple makes crazy profits from it, but doesn't want to open-source it -- still, Linux (in the form of Android) is more popular.

**Comment by cesss** [comment]
@bugaevc In fact the copyleft vs copyright discussion doesn't have practical/tech roots. There's a deeper root in the debate. However, when writing my point above, I focused in a practical consequence of such choice, and that's the reason why I said  _if Darling had some use (as a lib, for example) inside another software_. The GNU promoters acknowledge the practical difference between software meant to be used by _end-users_ and software meant to be used by _developers_ as a component inside another software project.

The only reason why the LGPL exists is because GNU promoters realized the freedom limits imposed by the GPL would be found not acceptable by quite a few developers when using third-party libraries or code. If the GPL was abandoned within libraries, the copyleft cause would be harm, so they introduced LGPL as a half-copyleft that could help push the cause even in such scenarios.

Note that the GPL-success examples you mention are end-user based. Note also that end-users don't usually worry about licenses (otherwise closed source wouldn't have more users than open source). If you think about _developer_ reusable code, you'll soon find examples where the choice of a copyright license helped the project to become widespread both in copyright and in copyleft environments (X11 just to name one), while if they had chosen a copyleft license, they would limit the potential number of developers using it.

When choosing libraries for my projects, I _always_ require them to _not_ be copyleft (not even LGPL). When choosing applications, I prefer non-copyleft because I never know if I'll have some idea in the future about starting a derived project from it. But I use some GPLed applications when there's no MIT/BSD alternative, or when they are unique in their class (as Darling is, for example).

Back to Darling, I insist the effort done deserves to be rewarded, and it's always the developers who must choose if it's copylefted or not. From my perspective, I can use Darling even if it is GPLed. But, if at some point, Darling becomes a sort of library or reusable component, is quite unlikely I'll use it for starting a new project (although I'll use it as a standalone application, of course).
