### ISSUE TITLE
getpwnam/getpwuid work only for root/0 under fake sudo

### ISSUE THREAD

**Issue by stek29** [darlinghq/darling#354]
```
Darling [~]$ touch file
Darling [~]$ chown user file
Darling [~]$ sudo chown user file
chown: user: illegal user name
```

See https://github.com/darlinghq/darling-file_cmds/blob/master/chown/chown.c#L252-L273 for relevant chown source code

When parsing uid from char*str coming from cmdline, it calls a_uid(str).
It tries to get uid from getpwnam(str), but if it returns NULL, it calls id(str, "user")
and id tries to convert it to uid with strtoul.
If it fails too, "illegal user name" is printed.

Now, if I add printfs for debugging purposes, I can see that in both cases str is "user".
However, when running as root, getpwnam() fails.

Then I tried to use Apple's chown binary from macOS and it failed too.

So, I wrote a simple program to test getpwnam/getpwuid:

```c
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
  uid_t uid;

  if (argc != 2)
    uid = getuid();
  else
    uid = atol(argv[1]);

  printf("uid: %lu\n", uid);

  struct passwd *pwd;
  pwd = getpwuid(uid);

  if (pwd == NULL) {
    printf("getpwuid fail : %s\n", strerror(errno));
    return 1;
  }

  printf("getpwuid pass : pw_name=%s\n", pwd->pw_name);

  const char *uname = strdup(pwd->pw_name);
  pwd = getpwnam(uname);
  free(uname);

  if (pwd == NULL) {
    printf("getpwnam fail : %s\n", strerror(errno));
    return 1;
  }

  printf("getpwnam pass : pw_uid=%lu\n", pwd->pw_uid);

  return 0;
}
```

Here are test results:
```
Darling [~]$ ./passwd_test
uid: 1000
getpwuid pass : pw_name=user
getpwnam pass : pw_uid=1000
Darling [~]$ ./passwd_test 0
uid: 0
getpwuid pass : pw_name=root
getpwnam pass : pw_uid=0
Darling [~]$ sudo ./passwd_test
uid: 0
getpwuid pass : pw_name=root
getpwnam pass : pw_uid=0
Darling [~]$ sudo ./passwd_test 1000
uid: 1000
getpwuid fail : Undefined error: 0
```

So, you can clearly see that getpw* fails under fake sudo.

**Comment by bugaevc** [comment]
[Turns out](https://www.freebsd.org/cgi/man.cgi?query=master.passwd) BSD has `/etc/master.passwd` in addition to `/etc/passwd`; `master.passwd` is the full version that includes passwords and whatnot, and it's only readable by root; `/etc/passwd` is readable by others (everyone?) & it gets auto-generated from the `admin.passwd` file by removing the secret fields.

So when running as (fake) root, `getpwuid()` reads `/etc/master.passwd`. We currently install [this dummy version](https://github.com/darlinghq/darling/blob/master/src/libinfo/master.passwd) that only lists root (which is why resolving root / UID 0 works) & symlink `/etc/passwd` from the host.

`master.passwd` and `passwd` differ in format, so simply symlinking `master.passwd -> passwd` doesn't do the trick. We could patch `libinfo` to never look at `master.passwd`...

**Comment by ahyattdev** [comment]
I think the best solution is putting the files that would be expected on macOS in place.

**Comment by bugaevc** [comment]
The problem with doing that is, of course, that we don't know the list of users in advance.

Here are some things that are nice to have, but maybe not mandatory:

* All Linux users to be visible from Darling, e.g. for `ls` to list their files properly
* Handling the situations when the list of users changes (after installing Darling, after first creating the prefix, after starting the container); the only sensible way to do that is to read the up-to-date info about users from host's `/etc/passwd` each time it's requested
* Making it seem there is an `admin` group that includes our user and root (#355), even though there is likely no such group on the host (and what if there is?)

Just symlinking host's `/etc/passwd` through as we do now gives us 1 and 2 but not 3; it doesn't work at all for `/etc/master.passwd`.

**Comment by CuriousTommy** [comment]
**Disclaimer:** I don't actually have any knowledge on MacOS or a understanding of UNIX stuff beyond running basic programs on the terminal shell. Feel free to ignore if my advice is really bad.

> Just symlinking host's /etc/passwd through as we do now gives us 1 and 2 but not 3

A bit of a sidenote, but I noticed on a real mac that my username isn't located in either the `/etc/passwd` and `/etc/master.passwd`. Instead, it is located in `/var/db/dslocal/nodes/Default/users/my_username.plist`

> * All Linux users to be visible from Darling, e.g. for ls to list their files properly

Just to be clear, are you referring only to the normal users (the ones you can see in the login screen) or are you also referring to the user services (`qemu` and `pulse` for example).

Also, wouldn't `ls` just list the actual user ID if the user did not exist (unless I am missing something)?

>The problem with doing that is, of course, that we don't know the list of users in advance.

IMO, the only user we need to care about is the one that that is calling the `darling` command (the one that starts up the container). If the `.darling` folder was shared among different users, then I would understand the need for getting a list of multiple users.

**Comment by bugaevc** [comment]
That is what I mean by nice to have; we could get by with just displaying UIDs of other users.

If we can make OpenDirectory work, we could make it dynamically query host's `/etc`, I guess...

**Comment by Elronnd** [comment]
Only listing UIDs could break; imagine if on linux user 'bob' has UID 1001.  And then in the virtual macos installation a user 'alice' is created who also has UID 1001 (this is legal because the passwd lists are separate).  Then if you look at files owned by bob on the host, ls thinks they're owned by alice.

Here's what I propose: passwd and master.passwd aren't really normal files, but specials which are created on-demand by merging the host's passwd file with darling's in an intelligent way.

**Comment by bugaevc** [comment]
And how would we do that? FUSE?

**Comment by Elronnd** [comment]
Make it a character special or something.

**Comment by ahyattdev** [comment]
Folding into  #711
