### ISSUE TITLE
a tool like strace to fast detect crash

### ISSUE THREAD

**Issue by pxb1988** [darlinghq/darling#436]
hi guys,

currently, if I want to find out an  executable crash on darling, i have to put a lot of `printf("run point 111\n")` to source code, but it is painful.

Q1:
is there any tool/method/tutorial, to debugging an executable on darling ?
Q2:
is there any tool like `strace` we can run on Apple and Darling, compare the two output we can fast locate the bug ?

**Comment by bugaevc** [comment]
> is there any tool/method/tutorial, to debugging an executable on darling ?

Not really. There are some tricks that we know and use, it's one of those many things that we should document sometime... In general, you can use LLDB under Darling, it works pretty well now thanks to @lubosd's awesome work. For objc code, `NSObjCMessageLoggingEnabled` is pretty useful. Otherwise, yes, it's `printf()`'ing and `NSLog()`ging.

> is there any tool like strace we can run on Apple and Darling, compare the two output we can fast locate the bug ?

Not really. You can actually use `strace` with Darling processes (`strace -p PID` from the host) since Darling processes are normal Linux processes (and BSD processes, and Mach tasks...). On macOS there's the dtrace framework, I don't think it actually works on Darling, nor is ever expected to work (not sure about it though). We have a tool called `xtrace` that traces the emulated BSD and Mach syscalls like `strace`, but of course you cannot directly compare its output to anything dtrace outputs on macOS.
