### ISSUE TITLE
Curiosity question: Darling's Foundation vs. upstream?

### ISSUE THREAD

**Issue by npyl** [darlinghq/darling#466]
Hi,
this is just a curiosity question.

What is darling's Foundation version? How old is it compared to [upstream](https://github.com/gnustep/libs-base)?

Thank you for your great work,
Nick.

**Comment by bugaevc** [comment]
Hi! Since the Mach-O transition we no longer use GNUstep Base as our Foundation implementation; we have switched to the Apportable's Foundation.

* Upsides: it is much closer architecturally to the Foundation Apple ships, it mirrors many implementation details of Apple's Foundation, it can be (and is designed to be) used on top of CFLite, which we have also switched to.
* Downsides: it is not as complete, so we had to take back some code from GNUstep Base; it had quite a few bugs (we've fixed most of them by now, I believe); it's not maintaned (by Apportable).

The GitHub repo is still marked as a fork of GNUstep Base because we don't know of a way to change it easily.

**Comment by npyl** [comment]
I understand thank you.
One quick search led me to [this](https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339).

I am not sure if it would help! :)

**Comment by bugaevc** [comment]
Yes, we've considered deleting and recreating the repo, but decided it's not worth it. Thanks anyway! :smiley:

**Comment by CuriousTommy** [comment]
@bugaevc I think you should make a note about it on the readme file, so that people who are new and want to contribute are aware.

**Comment by ahyattdev** [comment]
https://github.com/darlinghq/darling-foundation/commit/3aa70984a7be6bc4c00d6d60c6204451889713f2

Good idea, I left a note
