### ISSUE TITLE
core dumped after run striped program

### ISSUE THREAD

**Issue by zqxiaojin** [darlinghq/darling#469]
Thank for bugaevc  and LubosD,  my application now can run at darling under lldb.

However, when I run it without lldb, it will crash.

Only has the following message:
> Segmentation fault: 11 (core dumped)

I can not collect the crash stack in darling, so I don't know why.

But when I debug it  step by step, it works well. 

After a few hours trying, I found seems it function create 20 pthead at one time may crash it.

Does some one have the same problem?

How can I collect the crash stack?

Maybe I should write a demo to try it.

**Comment by bugaevc** [comment]
What kind of application is this, a Cocoa app? A command-line Unix program?

Any chance you could post it so we could take a look?

**Comment by zqxiaojin** [comment]
That a command-line program with Cocoa runloop.

I will upload it tomorrow.

**Comment by zqxiaojin** [comment]
Finally , I found the different.

I upload the demo:
[TestDarling.zip](https://github.com/darlinghq/darling/files/2796643/TestDarling.zip)

When I run "TestDarling", it works well.
But when I strip it (as the file "TestDarling_after_strip"  , it run a few while and  crash.

I can run them both as my mac. 

How can I fix it?

**Comment by zqxiaojin** [comment]
Here is the source code and binary
[SourceCode.zip](https://github.com/darlinghq/darling/files/2796783/SourceCode.zip)
[binary.zip](https://github.com/darlinghq/darling/files/2796787/binary.zip)

**Comment by zqxiaojin** [comment]
I found that the NSRunLoop may be trapped  for sometime.
Is there some bug in NSRunloop?
Should I use other message loop instead?

**Comment by bugaevc** [comment]
> How can I fix it?

Don't! If it works under macOS, it should work under Darling as-is as well, and if it doesn't, it's our bug.

There may very well be a bug in `NSRunLoop`, let us investigate... (or do it yourself!)

**Comment by zqxiaojin** [comment]
> > How can I fix it?
> 
> Don't! If it works under macOS, it should work under Darling as-is as well, and if it doesn't, it's our bug.
> 
> There may very well be a bug in `NSRunLoop`, let us investigate... (or do it yourself!)

Do you means when we strip the program , the NSRunloop will crash ?

**Comment by LubosD** [comment]
We've seen many weird things in the past.... In general, if you set `ulimit -c unlimited`, you should be able to get a core dump. Then you can analyze it in LLDB.

I'll try to take a look myself.

**Comment by zqxiaojin** [comment]
> We've seen many weird things in the past.... In general, if you set `ulimit -c unlimited`, you should be able to get a core dump. Then you can analyze it in LLDB.
> 
> I'll try to take a look myself.

Where can I get the core dump file in darling ?

**Comment by LubosD** [comment]
It should be generated in the current directory, just like one Linux.

I did some debugging myself and found this:

```
2019-01-25 18:21:29.554 TestDarling_after_strip[137:3e8] willStart a delay performSelector after 1 seconds
Process 137 stopped
* thread #1, name = 'TestDarling_aft', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00007ffff54534bb
->  0x7ffff54534bb: movq   %rax, 0x8(%rdx)
    0x7ffff54534bf: movq   %rsi, 0x137002(%rip)
    0x7ffff54534c6: je     0x7ffff5452f9c
    0x7ffff54534cc: subq   $0x20, %r14
```

Then I looked at `/proc/???/maps` to find out that the crash happens in `libc.so`. IDA Pro then helped me locate that instruction in `sysmalloc()`, probably [this line](https://github.com/bminor/glibc/blob/master/malloc/malloc.c#L2671).

I printed the value of `$rdx`:
```
(lldb) p/x $rdx
(unsigned long) $0 = 0x00007ffff7ffefa0
```

and compared it to the `/proc/???/maps` output:

```
7ffff7ff9000-7ffff7fff000 r--p 00006000 fe:01 375600                     /Volumes/SystemRoot/home/lubos/issue-469/TestDarling_after_strip
7ffff7fff000-7ffff8020000 rw-p 00000000 00:00 0                          [heap]
```

For whatever reason, glibc's malloc-related structures end up pointing outside the [sbrk](https://en.wikipedia.org/wiki/Sbrk) (aka `[heap]`) space. I also captured the problem like this:

```
[pid   629] brk(NULL)                   = 0x7ffff7ffefa0
[pid   629] brk(0x7ffff801ffa0)         = 0x7ffff801ffa0
[pid   629] brk(0x7ffff8020000)         = 0x7ffff8020000
[pid   629] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7ffff7ffefa8} ---
```

So the wrong location is coming directly from the kernel. That means the bug is [somewhere in here](https://github.com/darlinghq/darling-newlkm/blob/master/darling/binfmt.c). Now it is also clear why stripping triggers the bug. Stripping makes the binary smaller, so the memory layout becomes different enough to make the bug appear.

I'll try to figure out why `brk(NULL)` returns this incorrect address for Mach-O processes.

**Comment by bugaevc** [comment]
Could this be the same as #462?

**Comment by LubosD** [comment]
@bugaevc Yes, looks like it.
