### ISSUE TITLE
New Contributor Portal

### ISSUE THREAD

**Issue by seesemichaelj** [darlinghq/darling#511]
I'm creating this issue due to the lack of any other way for new contributors to say hello, ask questions that are beyond the landing page, etc. It can be left as an open (and maybe a pinned) issue for other contributors to introduce themselves and figure out where their expertise is most effective (or what they're interested in).

It seems the IRC channel is no longer used for developer communication. Is there another communication media for developers to have these kinds of discussions? Github issues is a little heavy.

Hello! I'm really interested in improving the GUI support for Darling. Per the blog post, @bugaevc seems to have been spearheading this recently. Where can I help? Also what steps are necessary to get up to speed where you're at in development?

I do have plenty of C++ experience as well some experience with XCode, Objective-C, and iOS development.

**Comment by CuriousTommy** [comment]
I would also love to contribute as well, but I currently have to deal with finals next week. I don't really have a lot of experience with GUI, Graphics, or Audio, but I would love to implement the more simple API that can run through the terminal.

I will admit that I don't have prior experience with Objective-C, but I do have experience with other languages (C++, Python, and Java) and I am willing to learning Objective-C on the spot. In fact, I have been re-implementing `CNLabeledValue` on XCode to better understand Objective-C.

However, I do have a few questions/concerns:
- Since I installed MacOS on my machine, I have accepted the EULA agreement. Would this prevent me from being able to contribute to Darling?
- Is there a coding style guideline I should abide to?

**Comment by bugaevc** [comment]
> I'm creating this issue due to the lack of any other way for new contributors to say hello, ask questions that are beyond the landing page, etc. It can be left as an open (and maybe a pinned) issue for other contributors to introduce themselves and figure out where their expertise is most effective (or what they're interested in).

Hmm, what ways are you thinking about? We have a mailing list, an issue tracker, the IRC channel, and our personal emails are somewhat known. Maybe we should host Discourse or something?

> It seems the IRC channel is no longer used for developer communication. Is there another communication media for developers to have these kinds of discussions? Github issues is a little heavy.

The IRC channel was never, to my knowledge, been used to communicate between the team. First there was just @lubosd, then we became a team and created a Slack "workspace" (https://github.com/darlinghq/darling/issues/241). IRC is still available, but using it to talk to us needs prior arrangement, because otherwise we're unlike to be online when you are (I don't use my IRC client all that often).

> Hello! I'm really interested in improving the GUI support for Darling. Per the blog post, @bugaevc seems to have been spearheading this recently. Where can I help? Also what steps are necessary to get up to speed where you're at in development?

> I do have plenty of C++ experience as well some experience with XCode, Objective-C, and iOS development.

That sounds great! If you haven't yet, I suggest you get started by reading the other blog posts from our blog (especially my post about Mach-Os; it tangentially mentions many details about various parts of Darling), reading our wiki, getting comfortable with building and running Darling. Get to know your way around the codebase (some important places to look into: `src/startup`, `src/lkm`, `src/kernel`, `src/external/corefoundation`, `src/external/foundation`, `src/external/cocotron`).

Then pick some issue you notice, or one of the already reported ones here on GitHub, and try to debug/fix it. If you want to work on AppKit specifically, then you'd likely need to get your system set up properly to be able to run GUI apps (which is non-trivial for now); either try to figure it out yourself or talk to me somewhere (we could arrange to talk on IRC for example, or we could invite you to Slack).

> I would also love to contribute as well, but I currently have to deal with finals next week. I don't really have a lot of experience with GUI, Graphics, or Audio, but I would love to implement any simplistic APIs that can run through the terminal.

> I will admit that I don't have prior experience with Objective-C, but I do have experience with other languages (C++, Python, and Java) and I am willing to learning Objective-C on the spot. In fact, I have been re-implementing `CNLabeledValue` on XCode to better understand Objective-C.

That sounds great too! You can absolutely learn as you go (as long as you have _some_ developer / Unix background).

> * Since I installed MacOS on my machine, I have accepted the EULA agreement. Would this prevent me from being able to contribute to Darling?

No, not at all. Working or having worked for Apple would, I believe (but I'm not a lawyer); just using macOS/iOS as an end user is fine. See https://wiki.winehq.org/Developer_FAQ#Copyright_Issues

> * Is there a coding style guideline I should abide to?

Again, not really. Most of the code in Darling comes from third parties (Apple, GNU, Cocotron...) — the rule of thumb is to try to follow the same style the code around what you're editing is written is (except in Cocotron — their [lack of] style is ugly; I'm planning to reformat the whole Cocotron into [my preferred style](https://mastodon.technology/@bugaevc/100896162451862098o) instead, so you may just as well follow that).

**Comment by ErikEklund** [comment]
Just wanted to note that I have an interest of helping out as well. What has stopped me so far is a lack of experience in the inner workings of macOS (and linux), feels like I need to read up on a lot of areas to be useful. That said, I do have quite long developer experience. I think a "get started with Darling development"-tutorial would be great to get more people helping with the project :).

**Comment by seesemichaelj** [comment]
Thanks @bugaevc for the quick and detailed response!

>Hmm, what ways are you thinking about? We have a mailing list, an issue tracker, the IRC channel, and our personal emails are somewhat known. Maybe we should host Discourse or something?

Some ways are Slack/Discourse/Discord/Gitter/Spectrum. I think it's great y'all do have a Slack for internal discussions, and I see the benefit of keeping it closed to the public without explicit invite. However, Slack invite links can be set to not expire. The problem here is you potentially open up a door to people complaining stuff isn't working :man_shrugging: 

Perhaps this Github issue ([maybe pin it?](https://help.github.com/en/articles/pinning-an-issue-to-your-repository); don't think its a beta feature anymore) is sufficient for new contributors to introduce themselves, and ask where they can start helping out in different areas they're interested in (since it is a pretty large codebase). I'm not really proposing you should add another communication channel. This issue already has had a good amount of use of letting potential contributors speak up :)

>That sounds great! If you haven't yet, I suggest you get started by reading the other blog posts from our blog (especially my post about Mach-Os; it tangentially mentions many details about various parts of Darling), reading our wiki, getting comfortable with building and running Darling. Get to know your way around the codebase (some important places to look into: src/startup, src/lkm, src/kernel, src/external/corefoundation, src/external/foundation, src/external/cocotron).
>
>Then pick some issue you notice, or one of the already reported ones here on GitHub, and try to debug/fix it. If you want to work on AppKit specifically, then you'd likely need to get your system set up properly to be able to run GUI apps (which is non-trivial for now); either try to figure it out yourself or talk to me somewhere (we could arrange to talk on IRC for example, or we could invite you to Slack).

Great! Thanks a bunch! I would love to get an invite to Slack if possible (seesemichaelj@gmail.com), but I'll see what I can figure out myself for now.

Again, really appreciate the response @bugaevc!

**Comment by seesemichaelj** [comment]
>I think a "get started with Darling development"-tutorial would be great to get more people helping with the project :).

@ErikEklund I believe https://wiki.darlinghq.org/start does have quite a bit of documentation for getting started

**Comment by jamesu** [comment]
I keep hearing about this "mailing list" but I can't seem to find any direct mention of it on any of the darling sites. Is there a secret handshake one is meant to use to access it? ;)

**Comment by CuriousTommy** [comment]
I apologize if this is not the right place to ask. I wasn't sure if I should open a new issue to ask this question or not.

@bugaevc While I was messing around with XCode's auto fill feature, I noticed that it gave more information about the function argument then Apple's online documentation (In particular, whether a argument is nullable or not).

When I am implementing the class' header file, is it okay to apply the information that XCode's auto fill feature provides, or should I stick to Apple's online documentation only? 

What I currently do to check an argument's nullability is by looking at the Swift documentation and see if the variable contains a `?` or not.

---

Also, when it comes to Apple's official headers, I was under the impressions that I should **NEVER EVER** look at them. Is that actually the case (I just want to make sure)?

**Comment by bugaevc** [comment]
So again, I'm not a lawyer, but my understanding is that:

* It's fine to read / look at Apple's docs and Apple's headers
* It's not fine ("never ever") to *copy-paste* from Apple's (non-free) headers
* Xcode autocomplete is kind of a gray area; it's a way of automating looking at the header but it's also kind of copying definitions from the header

**Comment by jamesu** [comment]
You can also print out struct and class layouts in lldb, but I suspect that there's a chance that could also be considered some form of copyrighted derivative.

Also remember you cannot copyright knowledge itself, so if you know an argument is nullable it wouldn't be a problem for you to declare that in the header. But if you blindly went ahead and copy-pasted what is in the header, that would more likely be subject to copyright.

Disclaimer: also not a copyright lawyer. Also the final outcome of that Google vs Oracle lawsuit is sure to shake things about.

**Comment by CuriousTommy** [comment]
When it comes to Objective C, is it okay to call an init function within another init function?

For example:
```
- (instancetype)initForReadingWithData:(NSData *)data {
    return [self initForReadingFromData:data error:nil];
}

- (instancetype)initForReadingFromData:(NSData *)data 
                                 error:(NSError * _Nullable *)error {
    // Insert code stuff.
}
```

**Comment by bugaevc** [comment]
Yes. This is known as _convinience_ and _designated_ initializers: the convenience initializers do some setup (or just pass the default values) and then call the designated initializer (typically there's one). See [this](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/MultipleInitializers.html) and [this](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Initialization/Initialization.html#//apple_ref/doc/uid/TP40010810-CH6-SW3).

**Comment by ahyattdev** [comment]
We are trying out a discord. Here is the invite link: https://discord.gg/XRD3mQA

**Comment by ahyattdev** [comment]
I think that the Discord is helping serve this purpose by being a place of casual discussion.
