### ISSUE TITLE
Versioning and packaging

### ISSUE THREAD

**Issue by jamesbrink** [darlinghq/darling#537]
I am curious why there is not currently any kind of versioning in place. I maintain the AUR package for `darling-git`, but due to obvious ongoing development this package breaks regularly. I am currently looking into making a second package for more stable builds, but I am currently using git refs of last known working builds since there are not any version tags.

Is this something the core team would be willing to implement? 
Additionally if there is any interest in packaging I would be happy to assist for that as well. 

I don't know if there are any debian/ubuntu packages available from anyone yet but I think that could be helpful for new users wanting to use Darling. I have never built a `.dep` package but I am sure I can fumble my way through it :laughing:

**Comment by jamesbrink** [comment]
What I have ended up doing for Arch users in the AUR was creating a second package
https://aur.archlinux.org/packages/darling/
I labeled it as **stable**, but in reality this just means it builds.. its more stable than the git HEAD.

**Comment by JL2210** [comment]
@jamesbrink It's a `.deb` package, not a `.dep` package.

**Comment by jamesbrink** [comment]
@JL2210 typo, and yeah I saw there are some in this repo actually, but I don't know the state of them.

**Comment by ahyattdev** [comment]
@jamesbrink ideally every commit should be able to build. Some of the time when it's broken is my fault. I think we should run a CI server that is integrated into PRs and shows them with green checkmarks when they build fine. That would help us get better at this.

Anyway, back to versioning, it's difficult to draw a line in the sand and say "this is version x" because most changes are minor additions as opposed to the kind of milestones that would make headlines and warrant a release.

One solution we could do now is to arbitrarily start it at `v0.1` and once a month or so when we know `master` builds we can increment that by one. The version would be largely meaningless and just give package maintainers a commit ref that will build and something to put in the version field. What are your thoughts on this?

**Comment by jamesbrink** [comment]
@ahyattdev breakage is totally expected during development. I would recommend maybe some sort of semantic versioning. I am not 100% how that generally works outside of the major.minor.patch. guess it depends on roadmap and what not. I could probably setup circle-ci on a fork and get that wired up as time permits. I think we could even offer `.deb` and other linux binaries on successful builds to make life easier for people wanting to install the app.

**Comment by ahyattdev** [comment]
@jamesbrink I agree, that would be better. Problem is, we don't have a roadmap 😐. I think that would be possible if we develop some plans for what we want to accomplish and when. Right now it's just taking care of issues and help out wherever we want 😄.

I think our builds would time out if we tried a free cloud provider. I may get my hands on some hardware that would be perfect for this and would have the power to run builds for us.

Great idea, downloadable packages would greatly increase usage of Darling because compiling it a daunting task.

**Comment by jamesbrink** [comment]
@ahyattdev so travis was awful with timeouts and just random failures. I have been using circle-ci to build my little hacky docker container for darling

https://github.com/utensils/docker-darling
and here is the circle CI https://circleci.com/gh/utensils/docker-darling

You can see at one point I started using cache, but I had some 3+ hour builds :laughing: 
they have a 5 hour timeout on the free plan which is why I recommend it. I can look into some methods and options for caching traditional builds so we are not looking at 3 hours for each merge or commit. Even without versioning it would be a clear indicator of what is building and what is not.

**Comment by andyneff** [comment]
A little late to this conversation, but I maintain the RPMs files (that are already part of the source) and I to think that _some_ kind of version stamping would be nice. (Consequently, I also prefer circle ci :), and might be able to help some. Not 100% sure how to run tests that require a kernel module, but I bet we can figure that out)

@ahyattdev  Even if there is no roadmap, I totally agree with the monthly (or tri-monthly) idea. (I was actually thinking that exact idea when I found this issue). I see many big projects do this, and I as a user like it.

My two cents would be version numbers like "year.month" work really well, so "2019.08" and then we can add to that if we actually have a significant bug fix later that month, "2019.08.1" or just wait until "2019.09".

**Comment by ahyattdev** [comment]
Cool, I think we could do something like you suggested, `0.2019.08`. The leading zero allows for switching to a real versioning system in the future, because 2000 major versions is a lot 🙃

Within the next month I will be putting together a system to run CI builds for us!

**Comment by ahyattdev** [comment]
Made a release for it: https://github.com/darlinghq/darling/releases/tag/v0.2019.8

**Comment by ahyattdev** [comment]
If we forget to make a tag for a release please remind us on the Discord 😄 https://discord.gg/XRD3mQA
