### ISSUE TITLE
[CMake] Wrong linker being used for Mach-O cross compiling

### ISSUE THREAD

**Issue by magiruuvelvet** [darlinghq/darling#554]
I'm trying to build Darling on my Gentoo Linux. Clang is my default system compiler with custom patches. LLVM/LLD is my default ELF linker.

During building where it reaches the step it cross-compiles for Mach-O I noticed the wrong linker is being used resulting in funny error messages like this:

```plain
ld.lld: error: unknown argument '-dynamic', did you mean '-Bdynamic'
ld.lld: error: unknown argument '-dylib'
ld.lld: error: unknown argument '-arch'
ld.lld: error: unknown argument '-no_arch_warnings'
ld.lld: error: unknown argument '-dylib_install_name'
ld.lld: error: unknown argument '-compatibility_version'
ld.lld: error: unknown argument '-Z'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: unknown argument '-dylib_file'
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
```

I first was confused, but I figured out that the wrong linker is being invoked because I found out that the Apple ld was compiled earlier. I can workaround this problem my adding

```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fuse-ld=${CMAKE_BINARY_DIR}/src/external/cctools-port/cctools/ld64/src/x86_64-apple-darwin11-ld")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fuse-ld=${CMAKE_BINARY_DIR}/src/external/cctools-port/cctools/ld64/src/x86_64-apple-darwin11-ld")
```

to every CMake file which cross compiles for Mach-O, but that's pretty annoying.

Is this a bug or a incompatibility with my custom toolchain. I don't have GCC installed. My default "binutils" are the LLVM binutils.

```
$ clang -v
clang version 9.0.0 
Target: x86_64-pc-linux
Thread model: posix
InstalledDir: /usr/lib/llvm/9/bin
Found CUDA installation: /opt/cuda, version 10.1
```

My clang defaults to libc++ and compiler-rt.

**Comment by magiruuvelvet** [comment]
I unfortunately hit a point where I can't continue :(

```
Linking C shared library libsystem_kernel.dylib
Undefined symbols for architecture x86_64:
  "___bzero", referenced from:
      _sigexc_handler in sigexc.o
     (maybe you meant: ____bzero)
ld: symbol(s) not found for architecture x86_64
```

I managed to get most of the libraries compiled and linked by now.

**Comment by magiruuvelvet** [comment]
I'm giving up. CMake ignores the linker set in `use_ld64`. My CMake version is 3.15.2

I tracked this issue down to CMake being derp.

**Comment by ahyattdev** [comment]
Does this issue still occur?

**Comment by magiruuvelvet** [comment]
I just made a fresh recursive clone of the repo. I can't even build any longer. It dies very early. Here is a [log](https://hastebin.com/vasidexosa.coffeescript). I have too many custom patches included in clang and other build tools that this project can't handle. That's what I get for forking Gentoo and making my own messy distro which is an abomination between musl and glibc. I think that's not worth supporting. I eventually will figure it out of my own.

**Comment by bugaevc** [comment]
> clang defaults to strict ISO compliance (GNU extensions are disabled by default)
> libc++ is the default runtime library (i don't even have libstdc++ installed)

Here's a thing: while it's reasonable to expect that projects by GNU and others to work with any C compiler and any libc/c++ implementation, you cannot expect the same of Apple code — they are using one particular compiler (clang), make use of its specific features/extensions and add more features/extensions when they feel like it. We're just lucky GNU/Linux builds of clang come with all those features too, so we can just use whatever clang the system already has installed. But don't expect your custom clang to work.

> That's what I get for forking Gentoo and making my own messy distro which is an abomination between musl and glibc.

It's not your fault, really, it's Apple's. You could compile a de-customized clang specifically for building Darling — think of it as a cross-compiler.

**Comment by bugaevc** [comment]
On the other hand, if you run into things like `MAP_ANONYMOUS` not being defined in `libelfloader/native/threads.c`, it might be something wrong (such as a missing include) on our end — would be nice if you submitted fixes for those :slightly_smiling_face:

**Comment by magiruuvelvet** [comment]
I could take an attempt to add the missing header files. I got used to it anyway since most software I use has suddenly lots of missing includes when `_GNU_SOURCE` is not declared by the compiler. Most missing include problems can be solved by just declaring `_GNU_SOURCE`, but thats the wrong solution in my opinion. Too many developers think extensions are available by default instead of adding a `-std=gnuxx` compile flag to be 100% sure and stay on the safe side.

**Comment by ahyattdev** [comment]
I agree that vanilla clang is the best option. We use a lot of open source code from Apple and porting all of that to GCC is a large effort.

**Comment by bugaevc** [comment]
Let me say it again.

Software developers can decide what configurations they want to support. Some decide they support arbitrary systems conforming to the POSIX standard while only writing portable C that should be understood by any compiler. Some try to write mostly generic code but slip in a few bit that break on non-GNU toolchains/userlands/configurations. Some explicitly support one, or a few, particular system(s) and take advantage of its specifics.

It sounds like you've been dealing with software that is of the first kind, i.e. that tries to be quite portable. Not all software is like that. If all software was like that, there'd be no need for Darling to exist.

Most of Apple software can only be built for Darwin with clang, with other caveats. Do not expect it not to use inline asm or to use it conditionally because that "is not standard C". That's laughable considering Objective-C doesn't even have a standard and "whatever Apple's build of Clang in the latest Xcode beta does" is your closest approximation of one.

As @ahyattdev has said, modifying Apple code to fix all of this would be a large effort that is not worth anyone's time. Moreover, we have a policy of not modifying Apple's code unless we really have to (i.e. to integrate Darling specifics), including not fixing bugs in Apple code (because either the same bug is reproducible on macOS, so we have bug-to-bug compatibility, or some other component evidently has to be more resilient).
