### ISSUE TITLE
Unable to Compile Ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#727]
```
[ 98%] Building CXX object src/external/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/bytecode/LazyOperandValueProfile.cpp.o
/home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JSWrapperMap.mm:598:31: error: cannot initialize a parameter of type 'id<NSCopying>' with an rvalue of type 'Class'
            return m_classMap[cls] = [self classInfoForClass:class_getSuperclass(cls)];
                              ^~~
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JSWrapperMap.mm:27:
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JavaScriptCore/JavaScriptCore.h:29:
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JavaScriptCore/JavaScript.h:30:
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JSBase.h:34:
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/foundation/include/Foundation/Foundation.h:16:
In file included from /home/<USERNAME>/Downloads/darling-build/build/darling/src/external/foundation/include/Foundation/NSDecimalNumber.h:4:
/home/<USERNAME>/Downloads/darling-build/build/darling/src/external/foundation/include/Foundation/NSDictionary.h:76:61: note: passing argument to parameter 'key' here
- (void)setObject:(id)obj forKeyedSubscript:(id <NSCopying>)key;
                                                            ^
/home/<USERNAME>/Downloads/darling-build/build/darling/src/external/JavaScriptCore/API/JSWrapperMap.mm:601:23: error: cannot initialize a parameter of type 'id<NSCopying>' with an rvalue of type 'Class'
    return m_classMap[cls] = [[[JSObjCClassInfo alloc] initForClass:cls] autorelease];
                      ^~~
```

**Comment by Newbytee** [comment]
Also getting this on Fedora 32 beta.

**Comment by GurthPalarran** [comment]
I have the same problem Actually I know nothing about Objective-C++, but can we replace` return m_classMap[cls] = [self classInfoForClass:class_getSuperclass(cls)];` with` [m_classMap enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key, id  _Nonnull obj, BOOL * _Nonnull stop) {
            if (obj == cls) {
                m_classMap[obj] = [self classInfoForClass:class_getSuperclass(cls)];
            }
            }];
            return /*m_classMap[cls] =*/ [self classInfoForClass:class_getSuperclass(cls)];`

**Comment by bugaevc** [comment]
No.

First of all, this is JSC code, not our code, so we shouldn't be just changing it because we feel like so. There are good reasons to change Apple code, for example if it relies on some OS features that Darling absolutely cannot/doesn't support, then we can `ifdef` them out; or if we believe that the actual version Apple uses is different from what they publish (e.g. they strip TFB from CFLite), we may try to bring our version closer to what we believe Apple's version does.

Second, you're not supposed to mutate the map while you're iterating over it, that's just wrong.

Third, this would turn a fast lookup into a _O(n)_ iteration over all key/value pairs.

The proper way to fix this would be to figure out how it builds for Apple. Maybe they have since changed the code so it does `(id) cls`? Maybe they have a different definition of something?

**Comment by ahyattdev** [comment]
What version of `clang` are you using for 20.04?

`clang-9` is known to work, if that's available.

**Comment by ahyattdev** [comment]
After testing, this happens starting with `clang-10`. A simple cast to `(id<NSCopying>)` keeps the build going here. Will push a patch when it completes fully.
