### ISSUE TITLE
Add a note in the readme to stop people for asking why "App X" doesn't run

### ISSUE THREAD

**Issue by worg** [darlinghq/darling#79]
It's sad to see the issue tracker flooded with open issues regarding "app x won't run", "app y fails to start", "when will I be able to run photoshop/illustrator/ableton/whatever".

The issue tracker isn't a wishlist.

Offtopic: great work!

**Comment by BioMike** [comment]
Ok, I'm going to hijack this thread a bit.

I spend last week trying to get darling building on Gentoo through the overlay and finally managed yesterday evening to get it build (read: I'm not sure at the moment if things runs like they should). The overlay hasn't been touched since 2013 and is in a bad shape. Same seems to be happening to Darling (not toched since November last year). Darling-dmg is active (some help from the OSXCross guy there). 
Seeing that Wine is such a popular piece of software, Darling should have also such active user/developer base, and I think it can seeing the activity of the bug reports here.
I'm not such a big C/C++/OBJ-C programmer (have hardly written any lines for it), but I can help open it from Github and provide the tools to build an active community around it (and have some idea's about that as well). I think this is where the discussion should be going to. Please share your thoughts.

**Comment by LubosD** [comment]
Darling development is active in the darling-libsystem repository.

**Comment by BioMike** [comment]
Yes, it seems it does. Why was this approach chosen (to start a new repo for this) and not in the currend Darling code (or a git branch if it would be incompatible with the current code base)? I think a few more side projects could be started that would benefit Darling more (and enabling non-coders/users to help). Also maintenance of the current "stable" Darling code needs to be done. I bumped into bug #85, but it hasn't been handled yet, rendering Darwin not buildable with recent clang versions.

**Comment by LubosD** [comment]
This approach was chosen because it'll be more fitting for Darling to be a collection of repositories (different components, frameworks etc.) rather than a single huge repo.

I can only handle development in one area. Myself, still being the only developer, I cannot work on everything. Apart from this, I still have other projects (FatRat, Twinkle), a full-time job and a family.

So I have to resort to saying: patches (pull requests) are welcome. Or you have to wait until I get around doing something about it.

**Comment by BioMike** [comment]
Ok, that is clear. I've already forked the gentoo overlay and put my own fixes in there, expect some PRs soon for that one (I'm still doing some tests of my own there to make more improvements). I will do the same with the Darling repo.

Is there already a way to use the Darling-libsystem with the Darling repo? Or is that still too soon?

**Comment by LubosD** [comment]
That's waaaaaay to early. It compiles a lot of things, but there's no syscall emulation layer done. It can't even be loaded.

**Comment by BioMike** [comment]
Ok, good to know. ;)

**Comment by hdost** [comment]
Like @Xylemon  was saying about how WineHQ is working, would be be good, to try to add certain applications to some sort of Roadmap. 
Since there is a sort of migration by many MacOS users, where there aren't alternatives that you can use. For example they want to run fully in a Linux Distro, but applications such as "Skype For Business" are required by a client, right now what you'd have to do is run a full VM to run it (If you can) . In this case you could maybe run the windows version in Wine (Tested won't work). This could apply to programs which don't run on Windows at all.

**Comment by ahyattdev** [comment]
Note there now
