### ISSUE TITLE
Collaboration with Darling for static compilation for macOS?

### ISSUE THREAD

**Issue by ylluminate** [darlinghq/darling#833]
Would collaboration with Darling and/or the utilization of Darling facilitate macOS static compilation? Please note this discussion: https://github.com/vlang/v/issues/5374#issuecomment-643763091 for the implementation of native x64 code generation for macOS.

**Comment by facekapow** [comment]
Hi, I think you might be a bit confused as to what Darling is. Darling allows you to run macOS programs on a Linux system (like what Wine does for Windows programs).

It looks like what you’re trying to do is compile 100% static binaries for macOS. This is something that neither Apple nor Darling supports. For Apple, it’s a matter of backwards compatibility; for Darling, it’s a matter of not being able to run them: we need to be able to insert our libraries where Apple’s libraries would normally be; we can’t do that if the system library is statically linked.

Please don’t try to make your compiler create pure static libraries for macOS. As I mentioned before (and as someone else mentioned in that issue you linked), it’s highly discouraged by Apple to do so. We’ve had problems before with compilers that do this (e.g. the Go compiler; see #193).

May I ask why you want to create a purely static binary rather than dynamically link to system libraries as Apple recommends?

**Comment by ylluminate** [comment]
No, I completely get it. What I'm wondering about is whether or not `crt0` and `libSystem` are implemented somewhere in the Darling codebase as open source implementations that could be used in reverse and in a collaborative fashion (with updates that work on each subsequent macOS releases).

**Comment by bjorn3** [comment]
> What I'm wondering about is whether or not crt0 and libSystem are implemented somewhere in the Darling codebase as open source implementations that could be used in reverse and in a collaborative fashion

The `libSystem` of Darwin uses Linux syscalls.

**Comment by ylluminate** [comment]
While I'm not yet seeing how, @sheerun I can't help but wonder if the V x64 code, generation due to the stable libc presentation on Linux, could be used in some fashion here in a circuitous way? Hmmmm...

**Comment by bugaevc** [comment]
Hi @ylluminate!

By "collaboration with Darling", do you mean collaboration between the V language and the Darling project?

+1 to everything @facekapow said about static linking: please don't; it's a bad idea for a whole bunch of reasons, *and* it's completely unsupported, and doesn't reliability work, on Darwin.

> What I'm wondering about is whether or not crt0 and libSystem are implemented somewhere in the Darling codebase as open source implementations

The original crt0 and libSystem from Apple are open source; we use modified versions of those on/in Darling.

> The libSystem of Darwin uses Linux syscalls.

Of Darling, surely you mean :D

**Comment by ylluminate** [comment]
Thanks guys - again I think some people like to scratch their cerebral itches with "impossible" tasks and I don't like to discourage and instead, as noted, am trying to facilitate such exercises if they feel any value in them themselves. 😊

**Comment by facekapow** [comment]
If you *really* want do this, you could check out the Go compiler’s history. Like I mentioned before, we had issues with them before because they were create 100% static binaries, so you could try to see how they did it.

But once again, I cannot stress enough how much you **shouldn’t** do this.

**Comment by sheerun** [comment]
I agree with @facekapow

**Comment by bjorn3** [comment]
> > The libSystem of Darwin uses Linux syscalls.
> 
> Of Darling, surely you mean :D

:)
