### ISSUE TITLE
Dependencies are missing in fedora

### ISSUE THREAD

**Issue by litch0** [darlinghq/darling#896]
Hello, I found out that the build is broken to fedora 33 because of some missing dependencies that are:
`kernel-devel.x86_64` and `dkms.noarch`.
I discoverd this after trying to install and older version of thr rpm

**Comment by litch0** [comment]
Also because of that darling is not working the result of `darling shell`
```SHELL
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.9.8-200.fc33.x86_64
Failed to load the kernel module
```
here is a ls of /lib/modules
```SHELL
> ls /lib/modules
5.8.16-300.fc33.x86_64  5.8.18-300.fc33.x86_64  5.9.8-200.fc33.x86_64
```

**Comment by HinTak** [comment]
dkms is not a build equirement - it is just a packaging one.  kernel-devel yes. On fedora with secure boot you need to sign your kernel module to be able to load them.

**Comment by HinTak** [comment]
See my docs pull for some fedora related tips : https://github.com/darlinghq/darling-docs/pull/12

**Comment by HinTak** [comment]
The build instruction includes kernel-devel: https://github.com/darlinghq/darling-docs/blob/master/src/build-instructions.md

I see that you were probably trying to install the also year-old rpms for fedora 30. Afaik that won't work on fedora 33 / kernel v5.9 - I think v5.4+ required some adjustments so that darling module source from almost a year ago simply won't build (either manually or via dkms) against v5.9 .
