### ISSUE TITLE
Libjpeg.so.62 missing

### ISSUE THREAD

**Issue by jhay06** [darlinghq/darling#922]
Hi ,
  per testing java and opera.app they are looking to a library libjpeg.so.62 ,

already install jpeg and jpeg-turbo 

but still the library was not found
![image](https://user-images.githubusercontent.com/5191437/106848491-0bba3600-66ec-11eb-8cef-8bf1d6f72a8e.png)

**Comment by jhay06** [comment]
nvm it was on linux part not on darling. but got this error LSOpenURLswithRole

**Comment by facekapow** [comment]
Yeah, the `LSOpenURLsWithRole` error is just an unimplemented function. Instead of using the `open` command, try executing directly (e.g. if the name of the app is `Opera`, the command to run would be `./Opera.app/Contents/MacOS/Opera`). Anyways, if that's what I think it is (Opera the browser), it won't work right now. Darling's GUI support is still early.
