### ISSUE TITLE
container

### ISSUE THREAD

**Issue by alicera** [darlinghq/darling#997]
**Expected Result**
First, I intstall the cmake 
darling shell 
brew install cmake

Next time , I run macos env
darling shell 
it has the cmake

How to clear the cmake？  Does the darking like the docekr container？

**Comment by bugaevc** [comment]
No.

While Darling does work somewhat like Docker containers _in some ways_ — namely, it also uses namespacing features of the kernel for isolation, — there's no image and container concepts like in Docker. We use _one_ layer of overlayfs to overlay your prefix contents on top of the "stock" Darling chroot. I don't think there's any technical obstacle to having Docker-like stackable layers, but it's out of scope for Darling; you could try to implement it yourself.

The UX of Darling prefixes is much more like that of Wine prefixes: they are stateful, you can have multiple of them, they just live in the file system and are identified by their paths, not IDs. Set `DPREFIX=/path/to/new/prefix` to run an independent container that doesn't have your CMake installation.

Note that Darling prefixes are "pets, not cattle" (unlike Docker, which encourages you to create many ad-hoc containers and throw them away willy-nilly). You might be better off properly uninstalling CMake from your existing prefix instead of creating a separate one.
